import Head from 'next/head'
import Image from 'next/image'
import Footer from "../components/footer";
import {Avatar, Box, Container, Heading, HStack, Text} from "@chakra-ui/react";
import Header from "../components/header";

export default function Home() {
    return (
        <>
            <Container maxW={"container.md"}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.png"/>
                </Head>

                <Header/>


                <main>

                </main>
            </Container>
            <Footer/>
        </>
    )
}
